# Generated by Django 3.1.2 on 2020-10-26 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicnicBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandwiches', models.BooleanField()),
                ('bear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_tutorial.bear')),
            ],
        ),
    ]
