# Generated by Django 3.1.2 on 2020-10-27 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tutorial', '0003_auto_20201027_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Frameworks', to='django_tutorial.language'),
        ),
    ]
